name: DeployToGitHubPages
env:
  PUBLISH_DIR: Frieren2022Viewer/bin/Release/net6.0/publish/wwwroot
on:
  schedule:
    - cron:  '7 14,2 * * *'
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update data
      run: dotnet run --project Frieren2022Fetcher/Frieren2022Fetcher.csproj > Frieren2022Viewer/wwwroot/votes.json
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update data
        file_pattern: 'Frieren2022Viewer/wwwroot/votes.json'
        status_options: '--untracked-files=no'

    - name: Publish app
      run: dotnet publish Frieren2022Viewer/Frieren2022Viewer.csproj -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /Frieren2022Checker/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
