name: DeployToGitHubPages
env:
  PUBLISH_DIR: Frieren2022Viewer/bin/Release/net6.0/publish/wwwroot
C:\Users\koude\Frieren2022Viewer\bin\Release\net6.0\publish\wwwroot
on:
  push:
    branches: [ master ]
#     paths: 
#       - .github/workflows/cd-pages.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Publish app
      run: dotnet publish Frieren2022Viewer/Frieren2022Viewer.csproj -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /Frieren2022Checker/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
